### ISSUE TITLE
Cannot load device list

### ISSUE THREAD

**Issue by sedlons** [mwittig/pimatic-unipi-evok#10]
Raspbian Jessie with EVOK v2.0 on Neuron 103.

Crashing with this error: 

`[UniPiUpdateManager] Error: unable to get device status, exception caught: SyntaxError: Unexpected token o
18:59:56.813 [pimatic-unipi-evok] Error
18:59:56.813 [pimatic-unipi-evok]>    at Object.members.stack (/home/pi/pimatic-app/node_modules/pimatic-unipi-evok/node_modules/pimatic-plugin-commons/lib/index.js:250:100)
18:59:56.813 [pimatic-unipi-evok]>    at Object.members.rejectWithErrorString (/home/pi/pimatic-app/node_modules/pimatic-unipi-evok/node_modules/pimatic-plugin-commons/lib/index.js:155:21)
18:59:56.813 [pimatic-unipi-evok]>    at /home/pi/pimatic-app/node_modules/pimatic-unipi-evok/unipi-update-manager.coffee:155:20
18:59:56.813 [pimatic-unipi-evok]>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
18:59:56.813 [pimatic-unipi-evok]>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:512:31)
18:59:56.813 [pimatic-unipi-evok]>    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
18:59:56.813 [pimatic-unipi-evok]>    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:614:10)
18:59:56.813 [pimatic-unipi-evok]>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:689:18)
18:59:56.813 [pimatic-unipi-evok]>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:133:16)
18:59:56.813 [pimatic-unipi-evok]>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:10)
18:59:56.813 [pimatic-unipi-evok]>    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
18:59:56.813 [pimatic-unipi-evok]>    at processImmediate [as _immediateCallback] (timers.js:383:17)
18:59:56.823 [pimatic-unipi-evok] [UniPiUpdateManager] Error: unable to get device status, exception caught: SyntaxError: Unexpected token o`

**Comment by mwittig** [comment]
Thanks for looking into this. Seems like the issue only occurs with the recent version of evok.

**Comment by mwittig** [comment]
Release pimatic-unipi-evok@0.3.0
Thanks for your help with sorting the compatbility issues with Evok 2.0. Much appreciated!
