### ISSUE TITLE
Updating values from unipi doesn't work

### ISSUE THREAD

**Issue by sedlons** [mwittig/pimatic-unipi-evok#12]
Evok sending updates as array. Sometimes one dimensional / sometimes multidimensional.

Response example for input update: 
`20:04:45.469 [pimatic-unipi-evok] [UniPiUpdateManager] received update: [{"counter_modes": ["Enabled", "Disabled"], "glob_dev_id": 2, "modes": ["Simple", "DirectSwitch"], "value": 0, "circuit": "UART_3_2_01", "debounce": 50, "counter": 15, "counter_mode": "Enabled", "dev": "input", "mode": "Simple"}, {"circuit": "UART_3_2_01", "value": 0, "glob_dev_id": 2, "dev": "wd", "timeout": 5000, "was_wd_reset": 0, "nv_save": 0}]`

**Comment by mwittig** [comment]
Release pimatic-unipi-evok@0.3.0
Thanks for your help with sorting the compatbility issues with Evok 2.0. Much appreciated!
