### ISSUE TITLE
plugin issue since update to version 0.3.1

### ISSUE THREAD

**Issue by emeins** [mwittig/pimatic-unipi-evok#17]
Since update to version 0.3.1 the unipi devices are not functional anymore. The pimatic web frontend does not show the switches or sensors (only the box and the device name). I cannot add new unipi devices class unipi not available anymore. Version 0.2.10 worked well until update.
I also checked the direct unipi website which is also working well.

**Comment by emeins** [comment]
runnng evok version 1.0

**Comment by mwittig** [comment]
Is it possible for you to update to a newer version of evok?

**Comment by mwittig** [comment]
No feedback. Closing this for now. Please re-open if you wish to follow up
